x-base-consumer: &base-consumer
  build:
    context: .
    dockerfile: ./docker/consumer/Dockerfile
  image: pedroegg/rinha-2025:consumer
  networks:
    - backend
    - payment-processor
  volumes:
    - /rinha-backend-2025-venv:/rinha-backend-2025-venv
  environment:
    - ENV=production
    - PYTHONUNBUFFERED=1
  depends_on:
    app-setup:
      condition: service_completed_successfully
    api1:
      condition: service_started
    api2:
      condition: service_started
    redis:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: "0.15"
        memory: "30MB"

services:
  app-setup:
    build:
      context: .
      dockerfile: ./docker/setup/Dockerfile
    image: pedroegg/rinha-2025:setup
    hostname: app-setup
    networks:
      - backend
      - payment-processor
    volumes:
      - rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      - ENV=production
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"

  api1:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: pedroegg/rinha-2025:api
    hostname: api1
    networks:
      - backend
    ports:
      - 3031:3031 #uwsgi stats http port 3031
    volumes:
      - rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      - ENV=production
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_SECRET_KEY=rinha_backend_2025
      - PYTHONUNBUFFERED=1
    depends_on:
      app-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  api2:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: pedroegg/rinha-2025:api
    hostname: api2
    networks:
      - backend
    ports:
      - 3032:3031 #uwsgi stats http port 3031
    volumes:
      - rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      - ENV=production
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_SECRET_KEY=rinha_backend_2025
      - PYTHONUNBUFFERED=1
    depends_on:
      app-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"

  consumer1:
    <<: *base-consumer
    hostname: consumer1

  consumer2:
    <<: *base-consumer
    hostname: consumer2

  consumer3:
    <<: *base-consumer
    hostname: consumer3

  consumer4:
    <<: *base-consumer
    hostname: consumer4

  redis:
    image: redis:7.4.5-alpine
    hostname: redis
    networks:
      - backend
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - 6379:6379
    volumes:
      - type: tmpfs
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  nginx:
    image: nginx:1.25-alpine
    hostname: rinha-nginx
    ports:
      - 9999:9999
    networks:
      - backend
      - payment-processor
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api1
      - api2
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  rinha-backend-2025-venv: