services:
  app-setup:
    environment:
      - ENV=development

  api1:
    environment:
      - ENV=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: "no"

  api2:
    environment:
      - ENV=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: "no"

  redis:
    restart: "no"

  consumer1:
    environment:
      - ENV=development
    restart: "no"

  consumer2:
    environment:
      - ENV=development
    restart: "no"

  consumer3:
    environment:
      - ENV=development
    restart: "no"

  consumer4:
    environment:
      - ENV=development
    restart: "no"