version: "3.9"

services:
  app-setup:
    build:
      dockerfile: ./setup/Dockerfile
    image: pedroegg/rinha-2025:setup
    hostname: app-setup
    networks:
      - backend
      - payment-processor
    volumes:
      - /rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  app1:
    build:
      dockerfile: ./Dockerfile
    image: pedroegg/rinha-2025:latest
    hostname: app1
    networks:
      - backend
      - payment-processor
    ports:
      - 3031:3031 #uwsgi stats http port 3031
    volumes:
      - /rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      ENV: production
      FLASK_APP: main.py
      FLASK_ENV: production
      FLASK_DEBUG: 0
      FLASK_SECRET_KEY: rinha_backend_2025
      PYTHONUNBUFFERED: 1
    depends_on:
      app-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  app2:
    build:
      dockerfile: ./Dockerfile
    image: pedroegg/rinha-2025:latest
    hostname: app2
    networks:
      - backend
      - payment-processor
    ports:
      - 3032:3031 #uwsgi stats http port 3031
    volumes:
      - /rinha-backend-2025-venv:/rinha-backend-2025-venv
    environment:
      ENV: production
      FLASK_APP: main.py
      FLASK_ENV: production
      FLASK_DEBUG: 0
      FLASK_SECRET_KEY: rinha_backend_2025
      PYTHONUNBUFFERED: 1
    depends_on:
      app-setup:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    ports:
      - 9999:9999
    networks:
      - backend
      - payment-processor
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true